export const  fetchApi = [
    {
        _id:1 ,
        numb:1,
        Start:"03/",
        name:"Covid-Tracker",
        link:"https://github.com/luckmer/Covid-Tracker",
        images:[
            "https://imgur.com/giTYt5C.png",
            "https://imgur.com/3bctEr3.png",
            "https://imgur.com/yJHK9k7.png",
            "https://imgur.com/XadoD74.png",
            "https://imgur.com/3bctEr3.png",
        ],
    },
    {
        _id:2 ,
        numb:"02/",
        name:"Drawing-App" ,
        link:"https://github.com/luckmer/Drawing-App" ,
        images:[
            "",
            "",
            "",
            "",
            "",
        ],
    },
    {
        _id:3 ,
        numb:3,
        Start:"04/",
        name:"School-control" ,
        link:"https://github.com/luckmer/School-control" ,
        images:[
            "https://imgur.com/GaQGP0h.png",
            "https://imgur.com/iq8gPTk.png",
            "https://imgur.com/QgAxrMA.png",
            "https://imgur.com/ppHEl7e.png",
            "https://imgur.com/XGmj30G.png",
        ]
    },
    {
        _id:4 ,
        numb:4,
        name:"Jump_Game" ,
        link:"https://github.com/luckmer/Jump_Game" ,
        images:[
            "",
            "",
            "",
            "",
            "",
        ],
    },
    {
        _id:5 ,
        numb:5,
        name:"Calendar_JS" ,
        link:"https://github.com/luckmer/Calendar_JS" ,
        images:[
            "",
            "",
            "",
            "",
            "",
        ],
    },
    {
        _id:6 ,
        numb:6,
        Start:"02/",
        name:"E-commerce-Shop" ,
        link:"https://github.com/luckmer/E-commerce-Shop" ,
        images:[
            "https://i.imgur.com/iMqEQBi.png",
            "https://i.imgur.com/iR8nfzE.png",
            "https://i.imgur.com/bJ0wR0H.png",
            "https://i.imgur.com/nSoUZFu.png",
            "https://i.imgur.com/1OfqvHO.png",
        ],
    },
    {
        _id:7 ,
        numb:7,
        name:"Snake_Game" ,
        link:"https://github.com/luckmer/Snake_Game" ,
        images:[
            "",
            "",
            "",
            "",
            "",
        ],
    },
    {
        _id:8 ,
        numb:8,
        name:"pick-an-apple-game" ,
        link:"https://github.com/luckmer/pick-an-apple-game" ,
        images:[
            "",
            "",
            "",
            "",
            "",
        ],
    },
    {
        _id:9 ,
        numb:9,
        name:"Flappy-Bird",
        link:"https://github.com/luckmer/Flappy-Bird" ,
        images:[
            "",
            "",
            "",
            "",
            "",
        ],
    },
    {
        _id:10 ,
        numb:10,
        name:"S-S-game" ,
        link:"https://github.com/luckmer/S-S-game" ,
        images:[
            "",
            "",
            "",
            "",
            "",
        ],
    },
    {
        _id:11 ,
        numb:11,
        name:"Dino-game" ,
        link:"https://github.com/luckmer/Dino-game" ,
        images:[
            "",
            "",
            "",
            "",
            "",
        ],
    },
    {
        _id:12 ,
        numb:12,
        name:"whack-a-mole" ,
        link:"https://github.com/luckmer/whack-a-mole" ,
        images:[
            "",
            "",
            "",
            "",
            "",
        ],
    },
    {
        _id:13 ,
        numb:13,
        Start:"01/",
        name:"country-information" ,
        link:"https://github.com/luckmer/country-information-" ,
        images:[
            "https://i.imgur.com/A1kkt3p.png",
            "https://imgur.com/ZydhwOl.png",
            "https://imgur.com/T9c1xtR.png",
            "https://imgur.com/bLkQOti.png",
            "https://i.imgur.com/A1kkt3p.png",
        ],
    },
]