export const fetchApi = [
    {
        _id: 1,
        numb: 1,
        Start: "03",
        name: "Covid-Tracker",
        filter: "Design",
        link: "https://github.com/luckmer/Covid-Tracker",
        images: [
            "https://imgur.com/DJyWdt1.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
        ],
    },
    {
        _id: 2,
        numb: "02",
        name: "Drawing-App",
        filter: "Games",
        link: "https://github.com/luckmer/Drawing-App",
        images: [
            "https://imgur.com/DJyWdt1.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
        ],
    },
    {
        _id: 3,
        numb: 3,
        Start: "04",
        name: "School-control",
        filter: "Design",
        link: "https://github.com/luckmer/School-control",
        images: [
            "https://imgur.com/DJyWdt1.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
        ],
    },
    {
        _id: 4,
        numb: 4,
        name: "Jump_Game",
        filter: "Games",
        link: "https://github.com/luckmer/Jump_Game",
        images: [
            "https://imgur.com/DJyWdt1.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
        ],
    },
    {
        _id: 5,
        numb: 5,
        name: "Calendar_JS",
        filter: "Design",
        link: "https://github.com/luckmer/Calendar_JS",
        images: [
            "https://imgur.com/DJyWdt1.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
        ],
    },
    {
        _id: 6,
        numb: 6,
        Start: "02",
        name: "E-commerce-Shop",
        filter: "Design",
        link: "https://github.com/luckmer/E-commerce-Shop",
        images: [
            "https://imgur.com/DJyWdt1.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
        ],
    },
    {
        _id: 7,
        numb: 7,
        name: "Snake_Game",
        filter: "Games",
        link: "https://github.com/luckmer/Snake_Game",
        images: [
            "https://imgur.com/DJyWdt1.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
        ],
    },
    {
        _id: 8,
        numb: 8,
        name: "pick-an-apple-game",
        filter: "Games",
        link: "https://github.com/luckmer/pick-an-apple-game",
        images: [
            "https://imgur.com/DJyWdt1.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
        ],
    },
    {
        _id: 9,
        numb: 9,
        name: "Flappy-Bird",
        filter: "Games",
        link: "https://github.com/luckmer/Flappy-Bird",
        images: [
            "https://imgur.com/DJyWdt1.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
        ],
    },
    {
        _id: 10,
        numb: 10,
        name: "S-S-game",
        filter: "Games",
        link: "https://github.com/luckmer/S-S-game",
        images: [
            "https://imgur.com/DJyWdt1.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
        ],
    },
    {
        _id: 11,
        numb: 11,
        name: "Dino-game",
        filter: "Games",
        link: "https://github.com/luckmer/Dino-game",
        images: [
            "https://imgur.com/DJyWdt1.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
        ],
    },
    {
        _id: 12,
        numb: 12,
        name: "whack-a-mole",
        filter: "Games",
        link: "https://github.com/luckmer/whack-a-mole",
        images: [
            "https://imgur.com/DJyWdt1.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
        ],
    },
    {
        _id: 13,
        numb: 13,
        Start: "01",
        name: "country-information",
        filter: "Design",
        link: "https://github.com/luckmer/country-information-",
        images: [
            "https://imgur.com/DJyWdt1.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
            "https://imgur.com/cDOnnKX.png",
            "https://imgur.com/wYbxwFj.png",
        ],
    },
];