export const  fetchApi = [
    {
        _id:1 ,
        numb:1,
        name:"Covid-Tracker",
        link:"https://github.com/luckmer/Covid-Tracker",
        images:{
            1:"https://imgur.com/giTYt5C.png",
            2:"https://imgur.com/3bctEr3.png",
            3:"https://imgur.com/yJHK9k7.png",
            4:"https://imgur.com/XadoD74.png",
            5:"https://imgur.com/3bctEr3.png",
        },
    },
    {
        _id:2 ,
        numb:2,
        name:"Drawing-App" ,
        link:"https://github.com/luckmer/Drawing-App" ,
        images:{
            1:"",
            2:"",
            3:"",
            4:"",
            5:"",
        },
    },
    {
        _id:3 ,
        numb:3,
        name:"School-control" ,
        link:"https://github.com/luckmer/School-control" ,
        images:{
            1:"https://imgur.com/GaQGP0h.png",
            2:"https://imgur.com/iq8gPTk.png",
            3:"https://imgur.com/QgAxrMA.png",
            4:"https://imgur.com/ppHEl7e.png",
            5:"https://imgur.com/XGmj30G.png",
        },
    },
    {
        _id:4 ,
        numb:4,
        name:"Jump_Game" ,
        link:"https://github.com/luckmer/Jump_Game" ,
        images:{
            1:"",
            2:"",
            3:"",
            4:"",
            5:"",
        },
    },
    {
        _id:5 ,
        numb:5,
        name:"Calendar_JS" ,
        link:"https://github.com/luckmer/Calendar_JS" ,
        images:{
            1:"",
            2:"",
            3:"",
            4:"",
            5:"",
        },
    },
    {
        _id:6 ,
        numb:6,
        name:"E-commerce-Shop" ,
        link:"https://github.com/luckmer/E-commerce-Shop" ,
        images:{
            1:"https://i.imgur.com/iMqEQBi.png",
            2:"https://i.imgur.com/iR8nfzE.png",
            3:"https://i.imgur.com/bJ0wR0H.png",
            4:"https://i.imgur.com/nSoUZFu.png",
            5:"https://i.imgur.com/1OfqvHO.png",
        },
    },
    {
        _id:7 ,
        numb:7,
        name:"Snake_Game" ,
        link:"https://github.com/luckmer/Snake_Game" ,
        images:{
            1:"",
            2:"",
            3:"",
            4:"",
            5:"",
        },
    },
    {
        _id:8 ,
        numb:8,
        name:"pick-an-apple-game" ,
        link:"https://github.com/luckmer/pick-an-apple-game" ,
        images:{
            1:"",
            2:"",
            3:"",
            4:"",
            5:"",
        },
    },
    {
        _id:9 ,
        numb:9,
        name:"Flappy-Bird",
        link:"https://github.com/luckmer/Flappy-Bird" ,
        images:{
            1:"",
            2:"",
            3:"",
            4:"",
            5:"",
        },
    },
    {
        _id:10 ,
        numb:10,
        name:"S-S-game" ,
        link:"https://github.com/luckmer/S-S-game" ,
        images:{
            1:"",
            2:"",
            3:"",
            4:"",
            5:"",
        },
    },
    {
        _id:11 ,
        numb:11,
        name:"Dino-game" ,
        link:"https://github.com/luckmer/Dino-game" ,
        images:{
            1:"",
            2:"",
            3:"",
            4:"",
            5:"",
        },
    },
    {
        _id:12 ,
        numb:12,
        name:"whack-a-mole" ,
        link:"https://github.com/luckmer/whack-a-mole" ,
        images:{
            1:"",
            2:"",
            3:"",
            4:"",
            5:"",
        },
    },
    {
        _id:13 ,
        numb:13,
        name:"country-information" ,
        link:"https://github.com/luckmer/country-information-" ,
        images:{
            1:"https://i.imgur.com/A1kkt3p.png",
            2:"https://imgur.com/ZydhwOl.png",
            3:"https://imgur.com/T9c1xtR.png",
            4:"https://imgur.com/bLkQOti.png",
            5:"https://i.imgur.com/A1kkt3p.png",
        },
    },
]